title: SAO:MD:DC
author: ratsounds
twitter: ratsounds

description: > 
  ソードアート・オンライン メモリー・デフラグ (メモデフ) 火力計算機
  Unofficial Damage Calculator for Sword Art Online Memory Defrag (SAOMD)
  Don't worry, this is ratsounds' strategy guide.

show_excerpts: false
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
