title: SAO:MD:DC
url: https://ratsounds.github.io/saomddc/
author: ratsounds

description: > 
  ソードアート・オンライン メモリー・デフラグ (メモデフ) 火力計算機と攻略Tips
  Unofficial Damage Calculator and Tips & Tricks for Sword Art Online Memory Defrag (SAOMD)
  Don't worry, this is ratsounds' strategy guide.

twitter:
  username: ratsounds
  card: summary

image: https://ratsounds.github.io/saomddc/image/ss.jpg

show_excerpts: false
theme: minima

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
